### PR TITLE
Support for custom ProviderTypeSelector

### PR DESCRIPTION
**Pull request by devilicecream**
Added support for custom ProviderTypeSelectors. Using standard sprox naming for the `__provider_type_selector_type__` parameter.

### CODE REVIEW

**Comment by pylover** [comment]
Nice

**Comment by amol-** [comment]
Tnx for the patch,

Before merging it I would ask you to please check why travis is failing on it and add the class property to the docstring (as the docstring is used in TG documentation to provide available crud options).

Also I prefer it is renamed without __ as it is just a CrudRestController property which is not providing any magic behaviour. All other properties of CrudRestController are named without __ apart from __form_options__, __table_options__ and __setters__ which actually provide a magic way to do something is already possible when using the standard edit_*/new_*/table_* properties.

**Comment by devilicecream** [comment]
I updated the commit including the docstring and changing the parameter name as you suggested.

I have no idea why, but two tests were failing because of the sqlite3.OperationalError being reported as ``sqlite3.OperationalError`` instead of just ``OperationalError`` as it was in the previous tests. I just fixed the check in the tests, but I'll try to take a deeper look to see what's changing the previous behavior.

**Comment by amol-** [comment]
cherry picked and rebased into a single commit: https://github.com/TurboGears/tgext.crud/commit/87b545df7ed25d2b8a438ca3fd586f1ddb77b9e6

**Comment by amol-** [comment]
Released in 0.7.4

**Comment by devilicecream** [comment]
:+1:

**Pull request closed without merging**
